[package]
name = "sidecar"
version = "0.1.0"
edition = "2021"

[dependencies]
quack = { path = "../quack" }
clap = { version = "4.0.26", features = ["derive"] }
bincode = "1.3.3"
tokio = { version = "1", features = ["full"] }
socket2 = { version = "0.4.7", features = ["all"] }
libc = "0.2.137"
nix = { version = "0.25.0", features = ["socket"] }

[[example]]
name = "cc_proxy"
